--- @meta

---@class WebhookMessageAuthor
---@field id string
---@field username string
---@field avatar any|table
---@field discriminator string
---@field public_flags number
---@field flags number
---@field bot boolean
---@field global_name any|table
---@field clan any|table
---@field primary_guild any|table

---@class WebhookMessage
---@field type number
---@field content string
---@field mentions string[]
---@field mention_roles string[]
---@field attachments table[]
---@field embeds table[]
---@field timestamp string
---@field edited_timestamp any|table
---@field flags number
---@field components table[]
---@field id string
---@field channel_id string
---@field author WebhookMessageAuthor
---@field pinned boolean
---@field mention_everyone boolean
---@field tts boolean
---@field webhook_id string
