--- @meta

--- This file was generated by Google Gemini.

--- @class fs.ReadHandle
--- A handle to a file opened for reading.
--- Provides methods to read data from the file stream.
local ReadHandle = {}

--- Close the file handle, releasing any resources associated with it.
--- This should always be called when you are finished with the handle.
function ReadHandle.close() end

--- Read the remainder of the file.
--- @return string|nil content The remaining content of the file, or nil if the end of the stream has been reached.
function ReadHandle.readAll() end

--- Read the next line from the file.
--- @param withTrailing? boolean Whether to include the newline character at the end of the string. Defaults to false.
--- @return string|nil line The next line, or nil if the end of the stream has been reached.
function ReadHandle.readLine(withTrailing) end

--- Read a number of characters or a single character from the file.
--- When count is provided, it returns a string of that length.
--- When count is absent, it returns the numeric code of the next character.
--- @param count? number The number of characters to read.
--- @return string|number|nil result The characters read, or the character code if no count is provided. Returns nil if at the end of the stream.
function ReadHandle.read(count) end

--- Seek to a new position within the file, if supported.
--- Note: Not all read handles support seeking (e.g., network streams).
--- @param whence? "set"|"cur"|"end" Where to seek from. "set" is start of file, "cur" is current position, "end" is end of file. Defaults to "cur".
--- @param offset? number The offset to seek to. Defaults to 0.
--- @return number position The new position within the file.
function ReadHandle.seek(whence, offset) end

--- @class http.Response: fs.ReadHandle
--- The response object returned by a successful HTTP request.
--- It provides methods to read the response body and retrieve metadata like status codes and headers.
local Response = {}

--- Returns the response code and status message.
--- @return number code The HTTP status code (e.g., 200).
--- @return string message The HTTP status message (e.g., "OK").
function Response.getResponseCode() end

--- Returns the response headers.
--- @return table<string, string> headers A table where keys are header names and values are header values.
function Response.getResponseHeaders() end

--- Close the response handle, releasing any resources associated with it.
--- This should always be called when you are finished with the response.
function Response.close() end

--- Read the remainder of the response.
--- @return string|nil content The remaining content of the response, or nil if the end of the stream has been reached.
function Response.readAll() end

--- Read the next line from the response.
--- @param withTrailing? boolean Whether to include the newline character at the end of the string. Defaults to false.
--- @return string|nil line The next line, or nil if the end of the stream has been reached.
function Response.readLine(withTrailing) end

--- Read a number of characters or a single character from the response.
--- @param count? number The number of characters to read.
--- @return string|number|nil result The characters read, or the character code if no count is provided. Returns nil if at the end of the stream.
function Response.read(count) end

return Response
